[스택,큐,덱] 09월 14일
Altu-Bitu-3/Altu-Bitu-HyunahPark pull request #3
Opened 2022-09-14 13:53 UTC by hak2711

#### 내용 & 질문
> 제출합니다!

#### <기존 제출>
> 1918, 4889, 11866, 18115

2022-09-14 17:52 UTC, flowersayo reviewed
p1. 안녕하세요 현아님!!!!
1918번이 꽤 난이도 있는 문제였음에도 불구하고 너무 훌륭하게 잘 풀이해주셨어요🥺
지금 몇가지점들을 놓쳐서 ps를 받지는 못했는데요..!! 
아마 코멘트 받은 것들 한번씩 읽어보시면 금방 틀린부분 파악되실거라고 생각됩니당 :)  
내일 과제마감 이후에 1918번 관련한 문제 풀이 해결과정을 다룬 PDF 자료가 올라갈텐데
자료 참고하면서 한번 더 수정해보시면 좋을 것 같아요! 😊
p1 커멘트는 꼭 수정해주셨으면 하는 부분이고, p2,p3는 참고만해주셔도 괜찮습니다!
특히 p1커멘트를 받은 문제는 코드리뷰 다음날까지 수정을 해주셔야 제출이 인정된다는 점 참고 부탁드립니다! 코드 수정하시고 저 리뷰어로 호출해주세요~!
수고하셨습니다🤗💛

2022-09-14 17:52 UTC, flowersayo commented on 09월 09일 - 스택,큐,덱/1918.cpp
> +  map<char, int> m = {{'+', 1}, {'-', 1}, {'*', 2}, {'/', 2}};
p3. 오옹 연산자 우선순위를 지정하기 위해서 map을 사용해주셨네요!
사실 본 코드를 다른사람이 본다고 생각하면 해당 값이 의미하는 바가 무엇인지 정확하게 파악하기 힘들 수 있어요ㅠㅠ 만일 이부분을 함수화 했다면 가독성 측면에서 더 좋았을 것 같아요ㅎㅎ

2022-09-14 17:52 UTC, flowersayo commented on 09월 09일 - 스택,큐,덱/1918.cpp
> +  string input;
흠? input을 입력받는 코드가 없는 것 같아요(?!)

2022-09-14 17:52 UTC, flowersayo commented on 09월 09일 - 스택,큐,덱/1918.cpp
> +  return post;
p1. A+B*C-D/E 같은 백준 예제 입력 값을 넣어보시면 아시겠지만 모든 for 루프를 수행하고 난 이후에도 스택에 연산자가 남아있는 경우가 있을 수 있죠! 이부분에 대한 처리가 아직 없네요 ㅎㅎ

2022-09-14 17:52 UTC, flowersayo commented on 09월 09일 - 스택,큐,덱/1918.cpp
> +  }
문제 해결을 위한 기본 뼈대 및 알고리즘 해결절차는 정말 잘 세워주셨어요!
그러나 본 코드는 아쉽게도 크게 두가지의 이유로 통과되지 못하고 있네요! 
도움이 될만한 힌트 두개 첨부하오니 해결되시면 저 리뷰어로 다시 호출 부탁드려요😊

1. stack에서 아무런 조건확인 없이 바로 top, pop을 하는 건 위험해요! 수아 튜터님께서도 강의시간에 강조하신 부분이지만, 만일 스택이 비어있는 상태라면 어떻게 될까요?
2. 스택의 top 에 있는 값이 현재 연산자와 비교 했을때 우선순위가 같다면 어떻게 처리해주어야 할까요?

2022-09-14 23:27 UTC, hak2711 commented on 09월 09일 - 스택,큐,덱/1918.cpp
> +  }
백준에서 분명 통과한 코드가 코드 리뷰에서 왜 패스를 못 했을까 싶었는데 제가 백준에서 통과된 최종 코드가 아니라 중간 과정에서 작성한 코드를 올렸네요ㅜㅜㅜ 번거롭게 만들어 정말 죄송합니다. 코드 다시 올렸습니다. 다시 봐주시면 감사하겠습니다..!!

2022-09-14 23:31 UTC, hak2711 commented on 09월 09일 - 스택,큐,덱/1918.cpp
> +  }
저의 실수 때문에 시간 낭비를 하게 만든 것 같아 다시 한 번 정말 죄송합니다.. 마음이 너무 급했나봐요. 다음 번에는 더욱 꼼꼼히 확인해서 이런 일 없도록 하겠습니다!

2022-09-15 08:44 UTC, bsa0322 requested changes
**p1. 18115 코드리뷰 완료**
현아님 안녕하세요 😊 함수화 해서 문제 해결해주신 것 너무 좋아요!! ❤
메모리 사용 관해서 p1 코멘트 남겼는데, 수정 후 리뷰어로 호출 부탁드립니다! 수고하셨습니다 🥰

2022-09-15 08:44 UTC, bsa0322 commented on 09월 09일 - 스택,큐,덱/18115.cpp
> +  }
p3. 기술 거꾸로 저장해 주신 거 너무 좋아요! for문의 반복문 인자를 잘 활용하면, 조금 더 가독성 높은 코드가 될 것 같아요 🥰🥰

2022-09-15 08:44 UTC, bsa0322 commented on 09월 09일 - 스택,큐,덱/18115.cpp
> +  }
p1. 카드 번호를 deque에 넣어 사용해 주셨네요!!! 해당 부분도 for문의 반복문 인자를 잘 활용하면 해결할 수 있습니다 😊 메모리는 가급적 아끼면 더욱 좋겠죠 🔥

2022-09-15 14:22 UTC, jk0527 approved these changes
P3. 11866 코드리뷰 완료

현아님 안녕하세요!
저희가 준비한 샘플 코드랑 거의 비슷해서 제가 따로 드릴 말씀이 없네요! 로직도 코드도 완전 깔끔합니다!! 코멘트 드린 vector를 리턴하는 부분만 생각해주시면 좋을 것 같아요! 11866번은 이대로 머지하셔도 좋을 것 같아요!! 궁금한 점이 있으면 리뷰어 호출해주세요!

2022-09-15 14:22 UTC, jk0527 commented on 09월 09일 - 스택,큐,덱/11866.cpp
> +void josephus(queue<int> &q, vector<int> &deleted, int k)
이렇게 deleted vector를 만들어서 josephus에서 수정해도 좋지만 실제 코딩 테스트처럼 josephus에서 deleted vector를 만들어서 리턴해도 좋을 것 같아요!

2022-09-15 16:13 UTC, Minseo10 approved these changes
**P3.  4889 코드리뷰 완료**
안녕하세요 현아님! 주석과 코드 모두 깔끔하게 잘 작성하셨네요 👍 
사소한 코멘트 몇가지 남겼으니 참고해주세요! 이번 과제도 수고하셨습니다 😄

2022-09-15 16:13 UTC, Minseo10 commented on 09월 09일 - 스택,큐,덱/4889.cpp
> +    }
**P3**: if문 안에 continue를 쓰는 것도 좋지만, if-else if 문을 활용하면 조건들을 더 알아보기 편할 것 같아요!

2022-09-15 16:13 UTC, Minseo10 commented on 09월 09일 - 스택,큐,덱/4889.cpp
> +  while (input[0] != '-')
종료조건을 while문 조건식 안에서 해결하셔서 코드가 훨씬 간결해졌네요! 👍

2022-09-17 05:45 UTC, hak2711 commented on 09월 09일 - 스택,큐,덱/18115.cpp
> +  }
코드 수정하였습니다! 확인 부탁드려요. 코멘트 감사합니다!

2022-09-18 17:53 UTC, flowersayo commented
앗 확인이 늦었네요😢 코드가 덜 올라간거였군용..ㅎㅎ 수정된 코드 모두 좋아요 바로 머지하셔도 괜찮습니다! 수고하셨습니다 ~!

2022-09-18 18:20 UTC, bsa0322 commented on 09월 09일 - 스택,큐,덱/18115.cpp
> +  }
확인이 늦어 죄송합니다! 😭 지금 코드 좋습니다~! 수고하셨습니다 🔥🔥💘💘

2022-09-18 18:20 UTC, bsa0322 approved these changes

2022-09-19 11:24 UTC, merged